### ISSUE TITLE
Begin a dictionary/glossary of terms/use cases

### ISSUE THREAD

**Issue by sarah-mc** [DigitalPatterns/design-guidelines#2]
Define cases, processes, and tasks.

**Comment by sarah-mc** [comment]
This will require consultation with @aminmc @pixie79

**Comment by aminmc** [comment]
I think the aim of this glossary is to clearly outline what we mean by a case, what we mean by a process and what we mean by as task.  This is our domain language and we need to make sure we're all on the same page. 

Clearly explaining teams and roles as well.
