### ISSUE TITLE
Update Deploying BPMN to COP

### ISSUE THREAD

**Issue by GrahamAtCrossLtd** [DigitalPatterns/design-guidelines#31]
The instructions for deploying BPMN to COP is missing some information:

- Screenshot is from a previous version and it looks a little different now
- URL does not reflect the url you would need to use i.e. <environment>/camunda/engine-rest
- There is no information on how to get the correct bearer token - use postman with correct settings - a screenshot of that process as well would be really useful to someone using for the first time

**Comment by aminmc** [comment]
@GrahamAtCrossLtd /camunda/engine-rest is for eForms...not COP
